apiVersion: v1
data:
  DATABASE_HOST: cG9zdGdyZXM=
  DATABASE_NAME: cG9zdGdyZXM=
  DATABASE_PASSWORD: cG9zdGdyZXM=
  DATABASE_PORT: NTQzMg==
  DATABASE_USER: cG9zdGdyZXM=
kind: Secret
metadata:
  name: postgres-config
  namespace: devops-project
type: Opaque
---
apiVersion: v1
data:
  REDIS_HOST: cmVkaXMtbWFzdGVyLnJlZGlzLnN2Yy5jbHVzdGVyLmxvY2Fs
  REDIS_PASSWORD: MXZDanV4b1ZnYQ== 
  REDIS_PORT: NjM3OQ==
kind: Secret
metadata:
  creationTimestamp: "2024-11-01T19:50:45Z"
  name: redis-config
  namespace: devops-project
type: Opaque
