apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
  namespace: devops-project
spec:
  destination:
    namespace: devops-project
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
      images:
      - docker.io/kainlite/devops-project:replace_me
    path: manifests
    repoURL: https://github.com/kainlite/devops-project
    targetRevision: master
  syncPolicy: {}
