apiVersion: v1
kind: Service
metadata:
  name: devops-project
  namespace: devops-project
spec:
  selector:
    name: devops-project
  ports:
    - protocol: TCP
      name: web
      port: 8000
      targetPort: 8000
