apiVersion: v1
kind: Secret
metadata:
  name: redis
  namespace: "redis"
  labels:
    app.kubernetes.io/instance: redis
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redis
    app.kubernetes.io/version: 7.4.1
    helm.sh/chart: redis-20.2.1
type: Opaque
data:
  redis-password: "MXZDanV4b1ZnYQ=="
